Repository terraform-docs/terraform-docs, pull requests merged in 2020-09, with the labels that each got.

#310 Allow dependabot to update github action versions
  .github/dependabot.yaml
Labels: dependencies, enhancement

#319 Add Docker to dependabot file
  .github/dependabot.yaml
Labels: dependencies, docker

#245 Custom order of changelog items
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  scripts/chglog/CHANGELOG-full-history.tpl.md
  scripts/chglog/CHANGELOG-release-note.tpl.md
  scripts/chglog/config-full-history.yml
  scripts/chglog/config-release-note.yml
Labels: enhancement

#326 Enhance release scripts
  .github/workflows/release.yaml
  scripts/build/build-all-osarch.sh
  scripts/release/release-note.sh
  scripts/release/release.sh
Labels: cleanup

#327 Prevent segfault error if input arg is a file
  internal/cli/reader.go
  internal/cli/reader_test.go
Labels: bug

#328 Fix homebrew PR creation process
  .github/workflows/release.yaml
Labels: cleanup

#329 add missing `v` to tag
  README.md
Labels: cleanup, documentaion
