Repository terraform-docs/terraform-docs, pull requests merged in 2020-02, with the labels that each got.

#186 Do not escape markdown table inside module header
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/pretty.md
  examples/main.tf
  internal/pkg/print/json/json_test.go
  internal/pkg/print/json/testdata/json-EscapeCharacters.golden
  internal/pkg/print/json/testdata/json-NoInputs.golden
  internal/pkg/print/json/testdata/json-NoOutputs.golden
  internal/pkg/print/json/testdata/json-NoProviders.golden
  internal/pkg/print/json/testdata/json-OnlyHeader.golden
  internal/pkg/print/json/testdata/json-SortByName.golden
  internal/pkg/print/json/testdata/json-SortByRequired.golden
  internal/pkg/print/json/testdata/json.golden
  internal/pkg/print/markdown/document/document.go
  internal/pkg/print/markdown/document/document_test.go
  internal/pkg/print/markdown/document/testdata/document-EscapeCharacters.golden
  internal/pkg/print/markdown/document/testdata/document-IndentationAboveAllowed.golden
  internal/pkg/print/markdown/document/testdata/document-IndentationBellowAllowed.golden
  internal/pkg/print/markdown/document/testdata/document-IndentationOfFour.golden
  internal/pkg/print/markdown/document/testdata/document-NoInputs.golden
  internal/pkg/print/markdown/document/testdata/document-NoOutputs.golden
  internal/pkg/print/markdown/document/testdata/document-NoProviders.golden
  internal/pkg/print/markdown/document/testdata/document-OnlyHeader.golden
  internal/pkg/print/markdown/document/testdata/document-SortByName.golden
  internal/pkg/print/markdown/document/testdata/document-SortByRequired.golden
  internal/pkg/print/markdown/document/testdata/document-WithRequired.golden
  internal/pkg/print/markdown/document/testdata/document.golden
  internal/pkg/print/markdown/markdown.go
  internal/pkg/print/markdown/table/table.go
  internal/pkg/print/markdown/table/table_test.go
  internal/pkg/print/markdown/table/testdata/table-EscapeCharacters.golden
  internal/pkg/print/markdown/table/testdata/table-IndentationAboveAllowed.golden
  internal/pkg/print/markdown/table/testdata/table-IndentationBellowAllowed.golden
  internal/pkg/print/markdown/table/testdata/table-IndentationOfFour.golden
  internal/pkg/print/markdown/table/testdata/table-NoInputs.golden
  internal/pkg/print/markdown/table/testdata/table-NoOutputs.golden
  internal/pkg/print/markdown/table/testdata/table-NoProviders.golden
  internal/pkg/print/markdown/table/testdata/table-OnlyHeader.golden
  internal/pkg/print/markdown/table/testdata/table-SortByName.golden
  internal/pkg/print/markdown/table/testdata/table-SortByRequired.golden
  internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
  internal/pkg/print/markdown/table/testdata/table.golden
  internal/pkg/print/pretty/pretty_test.go
  internal/pkg/print/pretty/testdata/pretty-NoColor.golden
  internal/pkg/print/pretty/testdata/pretty-NoHeader.golden
  internal/pkg/print/pretty/testdata/pretty-NoInputs.golden
  internal/pkg/print/pretty/testdata/pretty-NoOutputs.golden
  internal/pkg/print/pretty/testdata/pretty-NoProviders.golden
  internal/pkg/print/pretty/testdata/pretty-OnlyHeader.golden
  internal/pkg/print/pretty/testdata/pretty-SortByName.golden
  internal/pkg/print/pretty/testdata/pretty-SortByRequired.golden
  internal/pkg/print/pretty/testdata/pretty.golden
  internal/pkg/print/settings.go
Labels: area/markdown-document, area/markdown-table, bug, section/header

#188 Add TestSettings for cleaner required Settings in tests
  Makefile
  go.mod
  go.sum
  internal/pkg/print/json/json_test.go
  internal/pkg/print/markdown/document/document_test.go
  internal/pkg/print/markdown/table/table_test.go
  internal/pkg/print/pretty/pretty_test.go
  internal/pkg/testutil/settings.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/LICENSE
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/modules.txt
Labels: refactoring

#189 Add support for YAML renderer
  README.md
  cmd/yaml.go
  docs/README.md
  docs/formats/README.md
  docs/formats/yaml.md
  go.mod
  go.sum
  internal/pkg/print/yaml/testdata/yaml-NoHeader.golden
  internal/pkg/print/yaml/testdata/yaml-NoInputs.golden
  internal/pkg/print/yaml/testdata/yaml-NoOutputs.golden
  internal/pkg/print/yaml/testdata/yaml-NoProviders.golden
  internal/pkg/print/yaml/testdata/yaml-OnlyHeader.golden
  internal/pkg/print/yaml/testdata/yaml-OnlyInputs.golden
  internal/pkg/print/yaml/testdata/yaml-OnlyOutputs.golden
  internal/pkg/print/yaml/testdata/yaml-OnlyProviders.golden
  internal/pkg/print/yaml/testdata/yaml-SortByName.golden
  internal/pkg/print/yaml/testdata/yaml-SortByRequired.golden
  internal/pkg/print/yaml/testdata/yaml.golden
  internal/pkg/print/yaml/yaml.go
  internal/pkg/print/yaml/yaml_test.go
  internal/pkg/tfconf/input.go
  internal/pkg/tfconf/module.go
  internal/pkg/tfconf/output.go
  internal/pkg/tfconf/position.go
  internal/pkg/tfconf/provider.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
Labels: area/yaml, document needed, new feature

#177 Render formatted results with go templates
  internal/pkg/print/json/json.go
  internal/pkg/print/markdown/document/document.go
  internal/pkg/print/markdown/table/table.go
  internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
  internal/pkg/print/pretty/pretty.go
  internal/pkg/print/pretty/testdata/pretty-NoInputs.golden
  internal/pkg/print/pretty/testdata/pretty-NoOutputs.golden
  internal/pkg/print/pretty/testdata/pretty-NoProviders.golden
  internal/pkg/print/pretty/testdata/pretty-OnlyHeader.golden
  internal/pkg/print/pretty/testdata/pretty-SortByName.golden
  internal/pkg/print/pretty/testdata/pretty-SortByRequired.golden
  internal/pkg/print/pretty/testdata/pretty.golden
  internal/pkg/tfconf/input.go
  internal/pkg/tfconf/provider.go
  internal/pkg/tmpl/template.go
Labels: area/json, area/markdown-document, area/markdown-table, area/pretty, document needed, enhancement, refactoring

#181 Link formats documentation in README
  README.md
Labels: documentaion

#192 Auto generate formats document from examples
  Makefile
  README.md
  cmd/json.go
  cmd/pretty.go
  cmd/root.go
  cmd/yaml.go
  docs/CONTRIBUTOR_GUIDE.md
  docs/README.md
  docs/USER_GUIDE.md
  docs/formats/README.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  docs/formats/pretty.md
  docs/formats/yaml.md
  scripts/docs/generate.go
Labels: documentaion

#193 Add tfconf.Options to load Module with
  cmd/json.go
  cmd/markdown.go
  cmd/pretty.go
  cmd/root.go
  cmd/yaml.go
  internal/pkg/testutil/testing.go
  internal/pkg/tfconf/module.go
  internal/pkg/tfconf/options.go
  scripts/docs/generate.go
Labels: enhancement, refactoring

#191 Extract and render output values from Terraform
  cmd/root.go
  examples/output_values.json
  internal/pkg/print/json/json_test.go
  internal/pkg/print/json/testdata/json-OutputValues.golden
  internal/pkg/print/markdown/document/document.go
  internal/pkg/print/markdown/document/document_test.go
  internal/pkg/print/markdown/document/testdata/document-IndentationBelowAllowed.golden
  internal/pkg/print/markdown/document/testdata/document-OutputValues.golden
  internal/pkg/print/markdown/table/table.go
  internal/pkg/print/markdown/table/table_test.go
  internal/pkg/print/markdown/table/testdata/table-OutputValues.golden
  internal/pkg/print/pretty/pretty.go
  internal/pkg/print/pretty/pretty_test.go
  internal/pkg/print/pretty/testdata/pretty-OutputValues.golden
  internal/pkg/print/settings.go
  internal/pkg/print/yaml/testdata/yaml-OutputValues.golden
  internal/pkg/print/yaml/yaml_test.go
  internal/pkg/testutil/testing.go
  internal/pkg/tfconf/module.go
  internal/pkg/tfconf/options.go
  internal/pkg/tfconf/output.go
  internal/pkg/tmpl/template.go
Labels: new feature, section/outputs

#204 Fix type conversion for numbers
  go.mod
  go.sum
  internal/types/bool_test.go
  internal/types/empty_test.go
  internal/types/list_test.go
  internal/types/map_test.go
  internal/types/nil_test.go
  internal/types/number_test.go
  internal/types/string_test.go
  internal/types/types.go
  internal/types/types_test.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/markdown.go
  vendor/modules.txt
Labels: bug

#207 Show sensitivity of the output value in rendered result
  cmd/root.go
  examples/output_values.json
  internal/format/document.go
  internal/format/json_test.go
  internal/format/pretty.go
  internal/format/table.go
  internal/format/testdata/document/document-OutputValues.golden
  internal/format/testdata/json/json-OutputValues.golden
  internal/format/testdata/pretty/pretty-OutputValues.golden
  internal/format/testdata/table/table-OutputValues.golden
  internal/format/testdata/yaml/yaml-OutputValues.golden
  internal/module/module.go
  internal/types/types.go
  pkg/tfconf/input.go
  pkg/tfconf/output.go
  pkg/tmpl/template.go
Labels: enhancement, section/outputs

#198 Add support for XML renderer
  README.md
  cmd/root.go
  cmd/xml.go
  docs/README.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  docs/formats/pretty.md
  docs/formats/xml.md
  docs/formats/yaml.md
  internal/format/testdata/xml/xml-NoHeader.golden
  internal/format/testdata/xml/xml-NoInputs.golden
  internal/format/testdata/xml/xml-NoOutputs.golden
  internal/format/testdata/xml/xml-NoProviders.golden
  internal/format/testdata/xml/xml-OnlyHeader.golden
  internal/format/testdata/xml/xml-OnlyInputs.golden
  internal/format/testdata/xml/xml-OnlyOutputs.golden
  internal/format/testdata/xml/xml-OnlyProviders.golden
  internal/format/testdata/xml/xml-OutputValues.golden
  internal/format/testdata/xml/xml-SortByName.golden
  internal/format/testdata/xml/xml-SortByRequired.golden
  internal/format/testdata/xml/xml.golden
  internal/format/xml.go
  internal/format/xml_test.go
  internal/types/types.go
  pkg/tfconf/input.go
  pkg/tfconf/module.go
  pkg/tfconf/output.go
  pkg/tfconf/position.go
  pkg/tfconf/provider.go
  scripts/docs/generate.go
Labels: documentaion, format/xml, new feature

#209 Add codecov report and badge
  .github/workflows/build.yaml
  .gitignore
  Makefile
  README.md
Labels: enhancement
