Repository terraform-docs/terraform-docs, pull requests merged in 2020-07, with the labels that each got.

#289 Build and push docker image
  .github/workflows/build.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  README.md
  scripts/release/release.sh
Labels: docker, documentaion, enhancement

#272 Add support for .terraform-docs.yml config file
  cmd/root.go
  docs/CONFIG_FILE.md
  docs/FORMATS_GUIDE.md
  docs/USER_GUIDE.md
  docs/formats/asciidoc-document.md
  docs/formats/asciidoc-table.md
  docs/formats/asciidoc.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  docs/formats/pretty.md
  docs/formats/tfvars-hcl.md
  docs/formats/tfvars-json.md
  docs/formats/tfvars.md
  docs/formats/toml.md
  docs/formats/xml.md
  docs/formats/yaml.md
  examples/.terraform-docs.yml
  internal/cli/annotations.go
  internal/cli/annotations_test.go
  internal/cli/config.go
  internal/cli/reader.go
  internal/cli/reader_test.go
  internal/cli/run.go
  internal/cli/testdata/sample-config.yaml
  internal/cli/util.go
  internal/cli/util_test.go
Labels: cmd/new flag, config-file, document needed, new feature

#293 Overall improvements to documentation
  CONTRIBUTING.md
  README.md
  docs/USER_GUIDE.md
Labels: documentaion

#299 Upgrade actions stages
  .github/workflows/build.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  Dockerfile
  README.md
Labels: enhancement

#300 Fix typo in README
  README.md
Labels: cleanup, documentaion
