Repository terraform-docs/terraform-docs, pull requests merged in 2020-03, with the labels that each got.

#213 Upgrade go to 1.14
  .github/workflows/build.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  go.mod
  vendor/modules.txt
Labels: enhancement

#214 Example git hook to keep module docs up to date
  docs/USER_GUIDE.md
Labels: documentaion

#216 Put reference to usage, cli, etc. in user guide
  docs/USER_GUIDE.md
Labels: documentaion

#217 Add support for fetching the module header from any file
  cmd/root.go
  docs/README.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  docs/formats/pretty.md
  docs/formats/xml.md
  docs/formats/yaml.md
  examples/doc.tf
  internal/format/document_test.go
  internal/format/json_test.go
  internal/format/pretty_test.go
  internal/format/table_test.go
  internal/format/testdata/document/document-HeaderFromFile.golden
  internal/format/testdata/json/json-HeaderFromFile.golden
  internal/format/testdata/pretty/pretty-HeaderFromFile.golden
  internal/format/testdata/table/table-HeaderFromFile.golden
  internal/format/testdata/xml/xml-HeaderFromFile.golden
  internal/format/testdata/yaml/yaml-HeaderFromFile.golden
  internal/format/xml_test.go
  internal/format/yaml_test.go
  internal/module/module.go
  internal/module/module_test.go
  internal/module/options.go
  internal/module/options_test.go
  internal/module/testdata/full-example/doc.tf
  internal/reader/lines.go
  internal/reader/lines_test.go
  internal/reader/testdata/no-traling-line.txt
  scripts/docs/generate.go
Labels: document needed, new feature, section/header

#218 Add installation guide for Windows users
  README.md
Labels: documentaion

#223 Allow hiding the "Sensitive" column in markdown
  cmd/markdown.go
  cmd/root.go
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  internal/format/document.go
  internal/format/document_test.go
  internal/format/table.go
  internal/format/table_test.go
  internal/format/testdata/document/document-OutputValuesNoSensitivity.golden
  internal/format/testdata/table/table-OutputValuesNoSensitivity.golden
  pkg/print/settings.go
Labels: cmd/new flag, new feature, section/outputs

#224 --no-header should not attempt reading main.tf file
  cmd/root.go
  internal/format/document_test.go
  internal/format/json_test.go
  internal/format/pretty_test.go
  internal/format/table_test.go
  internal/format/testdata/json/json-Empty.golden
  internal/format/testdata/xml/xml-Empty.golden
  internal/format/testdata/yaml/yaml-Empty.golden
  internal/format/xml_test.go
  internal/format/yaml_test.go
  internal/module/module.go
  internal/module/module_test.go
  internal/module/options.go
Labels: bug, section/header

#226 Add support for tfvars hcl and json commands
  README.md
  cmd/root.go
  cmd/tfvars.go
  docs/README.md
  docs/USER_GUIDE.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/pretty.md
  docs/formats/tfvars-hcl.md
  docs/formats/tfvars-json.md
  docs/formats/tfvars.md
  docs/formats/xml.md
  docs/formats/yaml.md
  go.mod
  go.sum
  internal/format/testdata/tfvars/hcl-EscapeCharacters.golden
  internal/format/testdata/tfvars/hcl-NoInputs.golden
  internal/format/testdata/tfvars/hcl-SortByName.golden
  internal/format/testdata/tfvars/hcl-SortByRequired.golden
  internal/format/testdata/tfvars/hcl.golden
  internal/format/testdata/tfvars/json-EscapeCharacters.golden
  internal/format/testdata/tfvars/json-NoInputs.golden
  internal/format/testdata/tfvars/json-SortByName.golden
  internal/format/testdata/tfvars/json-SortByRequired.golden
  internal/format/testdata/tfvars/json.golden
  internal/format/tfvars_hcl.go
  internal/format/tfvars_hcl_test.go
  internal/format/tfvars_json.go
  internal/format/tfvars_json_test.go
  internal/module/options.go
  internal/types/bool_test.go
  internal/types/empty_test.go
  internal/types/list_test.go
  internal/types/map_test.go
  internal/types/nil_test.go
  internal/types/number_test.go
  internal/types/string_test.go
  internal/types/types.go
  scripts/docs/generate.go
  vendor/github.com/iancoleman/orderedmap/LICENSE
  vendor/github.com/iancoleman/orderedmap/orderedmap.go
  vendor/github.com/iancoleman/orderedmap/readme.md
  vendor/modules.txt
Labels: cmd/new command, cmd/tafvars/hcl, cmd/tfvars, cmd/tfvars/json, format/tfvars/hcl, format/tfvars/json, new feature, section/inputs

#227 Enhance automatic document generation
  CONTRIBUTING.md
  README.md
  cmd/json.go
  cmd/markdown.go
  cmd/pretty.go
  cmd/root.go
  cmd/tfvars.go
  cmd/xml.go
  cmd/yaml.go
  docs/CONTRIBUTOR_GUIDE.md
  docs/FORMATS_GUIDE.md
  docs/USER_GUIDE.md
  docs/formats/json.md
  docs/formats/markdown-document.md
  docs/formats/markdown-table.md
  docs/formats/markdown.md
  docs/formats/pretty.md
  docs/formats/tfvars-hcl.md
  docs/formats/tfvars-json.md
  docs/formats/tfvars.md
  docs/formats/xml.md
  docs/formats/yaml.md
  scripts/docs/generate.go
Labels: documentaion
