Repository terraform-docs/terraform-docs, pull requests merged in 2021-02, with the labels that each got.

#377 Use goreleaser for release workflow and tasks
  .github/workflows/build.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  .gitignore
  .goreleaser.yml
  CONTRIBUTING.md
  Makefile
  README.md
  internal/version/version.go
  scripts/build/build-all-osarch.sh
  scripts/homebrew/README.md
  scripts/homebrew/terraform-docs.rb
  scripts/release/Dockerfile
  scripts/release/release.sh
  scripts/release/update-choco.sh
Labels: enhancement

#401 Fixed lexicographic sorting of resources
  internal/terraform/resource.go
  internal/terraform/resource_test.go
Labels: bug, section/resources

#404 Refactor docs to be published on website
  .github/workflows/ci.yaml
  README.md
  docs/CONFIG_FILE.md
  docs/FORMATS_GUIDE.md
  docs/_index.md
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/config-file.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  scripts/docs/format.tmpl
  scripts/docs/generate.go
Labels: documentaion, enhancement

#396 Update to go1.16
  .github/workflows/ci.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  go.mod
Labels: arch/arm64, enhancement

#406 Completely remove deprecated '--no-XXX' flags
  cmd/asciidoc/asciidoc.go
  cmd/json/json.go
  cmd/markdown/markdown.go
  cmd/pretty/pretty.go
  cmd/root.go
  internal/cli/config.go
Labels: deprecation
