Repository terraform-docs/terraform-docs, pull requests merged in 2021-09, with the labels that each got.

#556 Skip read lines from empty file
  internal/reader/lines.go
  internal/reader/lines_test.go
  internal/reader/testdata/empty.txt
Labels: size/S

#558 Restructure documentations
  .github/workflows/ci.yaml
  docs/_index.md
  docs/developer-guide/contributing.md
  docs/developer-guide/plugins.md
  docs/how-to/cli-flag-false-value.md
  docs/how-to/configuration-file.md
  docs/how-to/generate-terraform-tfvars.md
  docs/how-to/github-action.md
  docs/how-to/include-examples.md
  docs/how-to/insert-output-to-file.md
  docs/how-to/pre-commit-hooks.md
  docs/how-to/recursive-submodules.md
  docs/how-to/visibility-of-sections.md
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/content.md
  docs/user-guide/configuration/footer-from.md
  docs/user-guide/configuration/formatter.md
  docs/user-guide/configuration/header-from.md
  docs/user-guide/configuration/output-values.md
  docs/user-guide/configuration/output.md
  docs/user-guide/configuration/sections.md
  docs/user-guide/configuration/settings.md
  docs/user-guide/configuration/sort.md
  docs/user-guide/configuration/version.md
  docs/user-guide/how-to.md
  docs/user-guide/installation.md
  docs/user-guide/introduction.md
  internal/print/settings.go
  netlify.toml
  scripts/docs/format.tmpl
Labels: cleanup, documentaion, size/XXL

#561 Overhaul README and docs improvements
  README.md
  docs/developer-guide/plugins.md
  docs/how-to/pre-commit-hooks.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/content.md
  docs/user-guide/installation.md
  docs/user-guide/introduction.md
Labels: size/L

#564 docs: typo in README
  README.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/sections.md
Labels: cleanup, documentaion, size/M

#565 optionally process comments from tf files as description
  README.md
  cmd/root.go
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/settings.md
  internal/cli/config.go
  internal/terraform/module.go
  internal/terraform/module_test.go
  internal/terraform/options.go
  internal/terraform/testdata/read-comments/variables.tf
  scripts/docs/generate.go
Labels: config-file, size/L

#570 Add recursive to config and enable partial config override
  README.md
  cmd/root.go
  docs/how-to/recursive-submodules.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/recursive.md
  docs/user-guide/configuration/sections.md
  docs/user-guide/configuration/settings.md
  docs/user-guide/configuration/sort.md
  examples/.terraform-docs.yml
  internal/cli/run.go
  print/config.go
  print/config_test.go
Labels: size/L
