Repository terraform-docs/terraform-docs, pull requests merged in 2021-07, with the labels that each got.

#535 Add output-check flag option
  cmd/root.go
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  internal/cli/config.go
  internal/cli/run.go
  internal/cli/writer.go
  internal/cli/writer_test.go
Labels: size/M

#527 Ignore extracting versions from terraform.lock.hcl
  cmd/root.go
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  docs/user-guide/configuration.md
  internal/cli/config.go
  internal/terraform/module.go
  internal/terraform/module_test.go
  internal/terraform/options.go
Labels: size/M

#537 Process \n as line break in --output-template flag
  internal/cli/config.go
  internal/cli/config_test.go
Labels: size/XL

#539 Add new example for MacOs Install docs
  docs/user-guide/installation.md
Labels: size/XS

#540 Attempt looking up config file in .config folder
  docs/user-guide/configuration.md
  internal/cli/run.go
Labels: size/S

#542 Add support for generating Packer document
  go.mod
  go.sum
Labels: size/XS

#543 Upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS

#544 Properly format indented code blocks
  internal/template/sanitizer.go
  internal/template/testdata/section/complex.expected
  internal/template/testdata/section/complex.golden
Labels: size/M

#545 Bump docker images (alpine and golang)
  Dockerfile
  scripts/release/Dockerfile
Labels: size/XS
