Repository terraform-docs/terraform-docs, pull requests merged in 2022-07, with the labels that each got.

#625 Fix CI linting
  Makefile
Labels: size/XS

#626 Update dependancies
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  Makefile
  README.md
  docs/how-to/github-action.md
  format/generator.go
  go.mod
  go.sum
  internal/cli/writer.go
  internal/reader/lines_test.go
  internal/testutil/testing.go
  scripts/docs/generate.go
  scripts/release/Dockerfile
Labels: dependencies, size/M

#627 Update alpine to 3.16.1
  Dockerfile
  scripts/release/Dockerfile
Labels: docker, size/XS
