Repository terraform-docs/terraform-docs, pull requests merged in 2023-12, with the labels that each got.

#727 Update/vulns
  Dockerfile
  go.mod
  go.sum
Labels: dependencies, docker, size/XL

#695 Update container to Alpine 3.18.2 and Go 1.18.10
  Dockerfile
  scripts/release/Dockerfile
Labels: dependencies, docker, size/XS

#718 docs: fix two typos in the 'configuration' section of the documentation
  docs/user-guide/configuration/content.md
  docs/user-guide/configuration/output.md
Labels: documentaion, size/XS

#696 Bump golang to 1.18.10
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
Labels: dependencies, go, size/XS

#639 Fix spelling
  docs/how-to/recursive-submodules.md
Labels: documentaion, size/XS

#619 Move terraform-docs bin in a folder already in the Linux PATH
  README.md
Labels: documentaion, size/XS

#690 Add fish shell completion
  cmd/completion/completion.go
  cmd/completion/fish/fish.go
  docs/user-guide/installation.md
  internal/types/types.go
Labels: cmd/new command, cmd/completion, size/M, cmd/completion/fish

#673 Update dependencies
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  Makefile
  format/doc.go
  format/generator.go
  go.mod
  go.sum
  internal/types/types.go
  plugin/doc.go
  print/doc.go
  print/util.go
  scripts/docs/generate.go
  scripts/release/Dockerfile
  template/doc.go
  terraform/doc.go
Labels: dependencies, size/XXL

#731 Create dependabot file
  .github/dependabot.yml
Labels: dependencies, size/S
