Repository terraform-docs/terraform-docs, pull requests merged in 2024-05, with the labels that each got.

#770 Bugfix: Upgrade `hclv2` to allow `terraform-docs` to read HCL containing provider functions
  go.mod
  go.sum
  terraform/testdata/full-example/main.tf
Labels: size/M

#776 chore: update dependencies
  go.mod
  go.sum
Labels: dependencies, go

#749 Fix output values with null
  format/generator_test.go
  terraform/load.go
  terraform/load_test.go
  terraform/testdata/full-example/outputs.tf
Labels: size/M

#730 Update Dockerfile FROM command to use non-ambiguous container sources
  Dockerfile
  scripts/release/Dockerfile
Labels: docker, size/XS

#651 Ignore inputs with terraform-docs-ignore comment
  docs/how-to/generate-terraform-tfvars.md
  docs/how-to/github-action.md
  docs/how-to/ignore-resources.md
  docs/how-to/include-examples.md
  docs/how-to/insert-output-to-file.md
  docs/how-to/pre-commit-hooks.md
  docs/how-to/recursive-submodules.md
  examples/main.tf
  examples/outputs.tf
  examples/variables.tf
  go.mod
  terraform/load.go
  terraform/load_test.go
  terraform/testdata/full-example/main.tf
  terraform/testdata/full-example/outputs.tf
  terraform/testdata/full-example/variables.tf
  terraform/testdata/no-requirements/main.tf
  terraform/testdata/no-resources/main.tf
  terraform/testdata/read-comments/variables.tf
Labels: size/L

#777 chore: add release-cut workflow
  .github/workflows/cut-release.yml
  scripts/release/release.sh
Labels: github_actions, size/M

#778 Make main module doc generation optional when generating recursively
  README.md
  cmd/root.go
  docs/how-to/recursive-submodules.md
  docs/reference/asciidoc-document.md
  docs/reference/asciidoc-table.md
  docs/reference/asciidoc.md
  docs/reference/json.md
  docs/reference/markdown-document.md
  docs/reference/markdown-table.md
  docs/reference/markdown.md
  docs/reference/pretty.md
  docs/reference/terraform-docs.md
  docs/reference/tfvars-hcl.md
  docs/reference/tfvars-json.md
  docs/reference/tfvars.md
  docs/reference/toml.md
  docs/reference/xml.md
  docs/reference/yaml.md
  docs/user-guide/configuration.md
  docs/user-guide/configuration/recursive.md
  examples/.terraform-docs.yml
  internal/cli/run.go
  print/config.go
Labels: config-file, size/M
