Repository terraform-docs/terraform-docs, pull requests merged in 2024-09, with the labels that each got.

#753 add docker multiarch build
  .github/workflows/ci.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: arch/amd64, arch/arm64, docker, size/M

#797 ci: Use correct env var for repo owner
  .github/workflows/ci.yaml
  .github/workflows/prerelease.yaml
Labels: size/XS

#686 Fix: Let Docker image be built correctly for non-amd64 platforms
  Dockerfile
Labels: docker, size/XS

#787 feat: Replace <br> with <br /> for markdown syntax
  docs/reference/markdown-table.md
  format/testdata/markdown/table-Base.golden
  format/testdata/markdown/table-EscapeCharacters.golden
  format/testdata/markdown/table-IndentationOfFour.golden
  format/testdata/markdown/table-OutputValues.golden
  format/testdata/markdown/table-OutputValuesNoSensitivity.golden
  format/testdata/markdown/table-WithAnchor.golden
  format/testdata/markdown/table-WithRequired.golden
  format/testdata/markdown/table-WithoutDefault.golden
  format/testdata/markdown/table-WithoutType.golden
  template/sanitizer.go
  template/sanitizer_test.go
  template/template_test.go
  template/testdata/table/codeblock-html.markdown.expected
  template/testdata/table/complex-html.markdown.expected
Labels: size/M

#805 Update dependencies
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  .golangci.yml
  Makefile
  go.mod
  go.sum
Labels: dependencies, go, size/L

#806 Update typo in pre-commit-hooks.md
  docs/how-to/pre-commit-hooks.md
Labels: size/XS
